In [6]:
import numpy as np

#1
arr = np.full((3, 3), True)
print(arr)
#2
arr_1D = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
arr_2D = arr_1D.reshape(3, 3)
arr_2D[:, [0, 2]] = arr_2D[:, [2, 0]]  # Hoán đổi cột 1 và cột 3
print(arr_2D)
#3
arr_2D[[0, 1]] = arr_2D[[1, 0]]
print(arr_2D)
#4
arr_2D = arr_2D[::-1]
print(arr_2D)
#5
arr_2D = arr_2D[:, ::-1]
print(arr_2D)
#6
arr_2D_null = np.array([[1, 2, 3], [np.nan, 5, 6], [7, np.nan, 9], [4, 5, 0]])
has_nan = np.isnan(arr_2D_null).any()
print(f"Có giá trị NaN: {has_nan}")
#7
arr_2D_null[np.isnan(arr_2D_null)] = 0
print(arr_2D_null)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]
[[5 4 3]
 [2 1 0]
 [8 7 6]]
[[8 7 6]
 [2 1 0]
 [5 4 3]]
[[6 7 8]
 [0 1 2]
 [3 4 5]]
Có giá trị NaN: True
[[1. 2. 3.]
 [0. 5. 6.]
 [7. 0. 9.]
 [4. 5. 0.]]
